void 0===window.centovacast&&(window.centovacast={});void 0===window.centovacast.options&&(window.centovacast.options={});
void 0===window.centovacast.loader&&(window.centovacast.loader={attempts:0,external_jquery:!1,loaded:!1,ready:!1,widget_definitions:{},url:"",load_script:function(b){var a=document.createElement("script");void 0!==a&&(a.setAttribute("type","text/javascript"),a.setAttribute("src",b),void 0!==a&&document.getElementsByTagName("head")[0].appendChild(a))},load_widget:function(b){b=this.widget_definitions[b];null===b.ref&&(b.ref=b.define(jQuery))},jq_get_jsonp:function(b,a,e){return jQuery.ajax({type:"GET",
url:b,data:a,success:e,dataType:"jsonp"})},jq_ready:function(){this.ready=!0;for(var b in this.widget_definitions)"function"==typeof this.widget_definitions[b].init&&this.widget_definitions[b].init(jQuery)},jq_loaded:function(){this.external_jquery||jQuery.noConflict();jQuery.getJSONP=this.jq_get_jsonp;for(var b in this.widget_definitions)this.load_widget(b);this.loaded=!0;var a=this;jQuery(document).ready(function(){a.jq_ready()})},wait:function(){setTimeout(function(){window.centovacast.loader.check()},
100)},check:function(){"undefined"===typeof jQuery?(this.wait(),this.attempts++):this.jq_loaded()},get_script_data:function(b,a,e){var c=jQuery(b),d=!1;b={};var f,g,h;for(h in a)a.hasOwnProperty(h)&&(f=a[h],(g=c.data(f))?(b[f]=g,d=!0):b[f]="");g=c.attr("id");if(d)"string"!=typeof g&&(window.centovacast.next_unique_id=window.centovacast.next_unique_id?window.centovacast.next_unique_id+1:1,g=e+"_"+window.centovacast.next_unique_id,c.attr("id",g));else{if("string"!=typeof g||g.substr(0,e.length+1)!=
e+"_")return null;e=g.substr(e.length+1);d=null;for(h in a)if(a.hasOwnProperty(h)){f=a[h];null===d&&(d=f);var c=new RegExp("_"+h+"-([^_]+)"),l=c.exec(e);l&&(b[f]=l[1],e=e.replace(c,""))}b[d]=e}b.id=g;return b},init:function(){var b=document.getElementsByTagName("script"),b=b[b.length-1],b=void 0!==b.getAttribute.length?b.getAttribute("src"):b.getAttribute("src",2);b.match(/^https?:\/\//i)||(b=window.location.href);this.url=b.replace(/(\.(?:[a-z]{2,}|[0-9]+)(:[0-9]+)?\/).*$/i,"$1");(this.external_jquery=
"undefined"!==typeof jQuery)||this.load_script(this.url+"system/jquery.min.js");this.check()},add:function(b,a,e){this.widget_definitions[b]||(this.widget_definitions[b]={define:e,init:a,ref:null});this.loaded&&this.load_widget(b);this.ready&&a(jQuery)}},window.centovacast.loader.init());
window.centovacast.loader.add("player",function(b){b.extend(!0,window.centovacast.player.settings,window.centovacast.options.player);b(".cc_player").each(window.centovacast.player.load);window.centovacast.player.initialize_all()},function(b){window.centovacast.options.player=b.extend(!0,{},window.centovacast.options.player,window.centovacast.player?window.centovacast.player.config:null);return window.centovacast.player={pollcount:0,settings:{muses:{}},registry:{},inspector:!1,debug:!1,dbg:function(a){this.debug&&
console.log(a)},players:{muses:function(a,e){var c=window.centovacast.player,d=window.centovacast.player.settings.muses,f="string"==typeof e.skin?e.skin.replace(/[^A-Za-z0-9_-]+/g,""):"";f.length||(f="mcclean");e.skin=f=a.url+"muses/muses-"+f+".xml";c.dbg("streaminfo:");c.dbg(a);var g=c.restricted_extend({url:a.tuneinurl+("ShoutCast"==a.servertype?";":""),lang:"auto",codec:a.tuneinformat,volume:75,tracking:!1,skin:a.url+"muses/muses-"+f+".xml",title:a.title,jsevents:!1,welcome:"",introurl:"",autoplay:!1,
buffering:5},d);c.restricted_extend(g,e,!0);f=window.centovacast.player.build_query(g,!0);c.dbg("flashvars:");c.dbg(g);d=c.restricted_extend({swfurl:a.url+"muses/muses.swf",width:180,height:60,bgcolor:"#FFFFFF",wmode:"window",scale:"noscale",allowscriptaccess:"always"},d);c.dbg("extending:");c.dbg(d);c.dbg("with:");c.dbg(e);c.restricted_extend(d,e,!0);c.dbg("params:");c.dbg(d);return b("<object/>",{width:d.width,height:d.height,bgcolor:d.bgcolor}).append(b("<param/>",{name:"movie",value:d.swfurl})).append(b("<param/>",
{name:"flashvars",value:f})).append(b("<param/>",{name:"wmode",value:d.wmode})).append(b("<param/>",{name:"scale",value:d.scale})).append(b("<param/>",{name:"allowScriptAccess",value:d.allowscriptaccess})).append(b("<embed/>",{src:d.swfurl,flashvars:f,width:d.width,height:d.height,scale:d.scale,wmode:d.wmode,bgcolor:d.bgcolor,type:"application/x-shockwave-flash",allowscriptaccess:d.allowscriptaccess}))},jplayer:function(a,e){var c=e.skin;c&&c.length||(c="blue.monday");"custom"!=e.skin&&b("body").append(b("<link/>",
{rel:"stylesheet",type:"text/css",href:a.url+"jplayer/skin/"+c+"/css/jplayer."+c+".css"}));var d=window.centovacast.player,f=b("<div />",{"class":"jp-info-bar"});window.centovacast.next_unique_id=window.centovacast.next_unique_id?window.centovacast.next_unique_id+1:1;var g=window.centovacast.next_unique_id,h=b("<div />",{"class":"jp-controls"}).append(b("<button/>",{"class":"jp-play",role:"button",tabindex:0}).text("play")),l=b("<div />",{"class":"jp-volume-controls"}).append(b("<button/>",{"class":"jp-mute",
role:"button",tabindex:0}).text("mute")).append(b("<button/>",{"class":"jp-volume-max",role:"button",tabindex:0}).text("max volume")).append(b("<div/>",{"class":"jp-volume-bar"}).append(b("<div/>",{"class":"jp-volume-bar-value"}))),c=e.controlorder&&"volume,playback"==e.controlorder||0<=c.indexOf("pink.flag")?[l,h]:[h,l],k=b("<div />",{id:"cc_jplayer_"+g,"class":"jp-jplayer"});b("<div />",{"class":"jp-controls"}).append(b("<button/>",{"class":"jp-play",role:"button",tabindex:0}).text("play"));b("<div />",
{"class":"jp-volume-controls"}).append(b("<button/>",{"class":"jp-mute",role:"button",tabindex:0}).text("mute")).append(b("<button/>",{"class":"jp-volume-max",role:"button",tabindex:0}).text("max volume")).append(b("<div/>",{"class":"jp-volume-bar"}).append(b("<div/>",{"class":"jp-volume-bar-value"})));var q=b("<div />",{id:"cc_jp_container_"+g,"class":"jp-audio-stream",role:"application","aria-label":"media player"}).append(b("<div />",{"class":"jp-type-single"}).append(b("<div />",{"class":"jp-gui jp-interface"}).append(c[0]).append(c[1])).append(b("<div />",
{"class":"jp-details"}).append(b("<div/>",{"class":"jp-title","aria-label":"title"}).html("&nbsp;"))).append(b("<div />",{"class":"jp-no-solution"}).text("To play the media you will need to either update your browser to a recent version or update your Flash plugin."))).append(f),g=b("<div />").append(k).append(q),p;d.inspector&&(p=b("<div>").appendTo(g));var m=a.tuneinformat;switch(m){case "aac":m="m4a";break;case "ogg":m="oga"}var n={title:a.title};n[m]=a.tuneinurl+("ShoutCast"==a.servertype?";stream/1":
"");c=[a.url+"/jplayer/jplayer/jquery.jplayer.js"];d.inspector&&c.push(a.url+"/jplayer/add-on/jquery.jplayer.inspector.min.js");d.load_scripts({scripts:c,success:function(){var c=!1,d=0;k.jPlayer({ready:function(a){c=!0;k.jPlayer("setMedia",n);e.autoplay&&k.jPlayer("play")},playing:function(a){d=0;f.text("")},pause:function(){k.jPlayer("clearMedia");k.jPlayer("setMedia",n)},error:function(a){alert("Error: "+a.jPlayer.error.message+" "+a.jPlayer.error.hint+" ("+a.jPlayer.error.type+" context "+a.jPlayer.error.context+
")"+(a.jPlayer.error.type===b.jPlayer.error.URL_NOT_SET?"Y":"N"));c&&a.jPlayer.error.type==b.jPlayer.error.URL&&5>d?(d++,setTimeout(function(){k.jPlayer("setMedia",n).jPlayer("play")},1E3)):c&&a.jPlayer.error.type===b.jPlayer.error.URL_NOT_SET?k.jPlayer("setMedia",n).jPlayer("play"):(d=0,f.text("Error: "+a.jPlayer.error.message+" "+a.jPlayer.error.hint+" ("+a.jPlayer.error.type+" context "+a.jPlayer.error.context+")"+(a.jPlayer.error.type===b.jPlayer.error.URL_NOT_SET?"Y":"N")))},swfPath:a.url+"/jplayer/",
supplied:m,cssSelectorAncestor:"#"+q.attr("id"),preload:"none",wmode:"window",useStateClassSkin:!0,autoBlur:!1,keyEnabled:!0});p&&p.length&&p.jPlayerInspector({jPlayer:k})},error:function(a){alert("Failed to load required scripts: "+a)}});return g},wmp:function(a,e){var c=window.centovacast.player,d=window.centovacast.player.settings.wmp,f=c.restricted_extend({classid:"clsid:6BF52A52-394A-11D3-B153-00C04F79FAA6",width:320,height:68},d);c.restricted_extend(f,e);var g=c.restricted_extend({type:"application/x-mplayer2",
pluginspage:"http://www.microsoft.com/Windows/Downloads/Contents/MediaPlayer/",width:320,height:68,src:a.tuneinurl,filename:a.tuneinurl,autostart:0,showcontrols:1,showstatusbar:1,showdisplay:1},d);c.restricted_extend(g,e);d=c.restricted_extend({url:a.tuneinurl,autostart:0,showcontrols:1,showstatusbar:1,showdisplay:1,stretchtofit:1},d);c.restricted_extend(d,e);var c=b("<object/>",f),h;for(h in d)d.hasOwnProperty(h)&&b("<param/>",{name:h,value:d[h]}).appendTo(c);c.append(b("<embed/>",g));return c}},
load_scripts:function(a){var e=a.scripts.length,c=a.success,d=function(){e--;0>=e&&c&&c.apply(this)},f;for(f=0;f<e;f++)b.ajax({dataType:"script",cache:!0,url:a.scripts[f],success:d,error:a.error})},build_query:function(a,b){var c,d,f="";for(c in a)a.hasOwnProperty(c)&&(d=a[c],b&&"boolean"==typeof d&&(d=d?"true":"false"),f+=(f.length?"&":"")+encodeURIComponent(c)+"="+encodeURIComponent(d));return f},restricted_extend:function(a,b,c){if("object"!==typeof b||"object"!==typeof a)return a;for(var d in a)a.hasOwnProperty(d)&&
b.hasOwnProperty(d)&&(!c||null!==b[d]&&("string"!==typeof b[d]||0<b[d].length))&&(a[d]=b[d]);return a},generate_player:function(a,b){var c=b.webplayer;c||(c="muses");c=c.replace(/sc1$/,"");this.dbg("generate "+c+" player for "+a);this.players[c]?(c=(0,this.players[c])(b,this.registry[a]),this.get_container(a).empty().append(c)):this.player_error(a,"Unavailable","Unrecognized player type: "+c)},show_loading:function(a){this.dbg("player for "+a+" is now loading ...")},clear_loading:function(a){this.dbg("player for "+
a+" is no longer loading")},get_container:function(a){return b("#"+this.registry[a].id)},player_error:function(a,b,c){this.dbg("player error for "+a+": "+b+"; "+c);this.get_container(a).html('<span title="'+c+'">'+b+"</span>");if("function"==typeof this.settings.on_error_callback)this.settings.on_error_callback(c)},check_widgetid:function(a){a+="";if(!this.registry[a]){if(1==this.registry.length){for(var b in this.registry)a=b;return a}return""}return a},handle_json:function(a){this.dbg("handling json response");
if(a){var b=this.check_widgetid(a.rid);!b.length&&a.requestdata&&(b=this.check_widgetid(a.requestdata.rid));b.length?"error"==a.type?this.player_error(b,"Unavailable",a?a.error:"No JSON object"):this.generate_player(b,a.data[0]):(this.dbg("no widgetid?!"),this.dbg(a))}else this.dbg("no json?!"),this.dbg(a)},initialize:function(a){this.dbg("initializing "+a);var e=this;b.getJSONP(window.centovacast.loader.url+"external/rpc.php",{m:"streaminfo.get",username:this.registry[a].username,charset:this.registry[a].charset,
rid:a,mountpoint:this.registry[a].mount},function(a){e.handle_json(a)})},initialize_all:function(){for(var a in this.registry)"string"==typeof a&&this.initialize(a)},register:function(a){var b=a.id;this.dbg("registering "+b);this.registry[b]=a},load:function(){var a=window.centovacast.loader.get_script_data(this,{username:"username",skin:"skin",cs:"charset",mp:"mount",width:"width",height:"height",autoplay:"autoplay",controlorder:"controlorder"},"cc_player");window.centovacast.player.dbg(a);null!==
a&&(window.centovacast.player.register(a),window.centovacast.player.show_loading(a.id))}}});
